### ISSUE TITLE
Expose Marionette on the page

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#117]

**Comment by jasonLaster** [comment]
Yup.

**Comment by paulfalgout** [comment]
This line could be re-added https://github.com/marionettejs/marionettejs.com/commit/30bed2fa561c6ccebf098e152ca4ea74a9199136#diff-bf143c78bb4166795f80029d72a3ab4dL46

As long as the defer is in there it'll be non-blocking and shouldn't slow the page load.  Really since underscore, BB and Mn aren't used in the site they could each be loaded deferred.  Though I doubt they're slowing down much in the concat.
