### ISSUE TITLE
Add "The Case for Marionette.js"

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionettejs.com#300]
@benmccormick wrote a great post about "why" Mn
http://benmccormick.org/2014/12/02/the-case-for-marionette-js/.

We should re-purpose this content and add it to the website as separate pages that support the main content. This would give a great rationale for the Mn way

**Comment by benmccormick** [comment]
I talked about this with Jason on gitter briefly.  I'm happy to contribute the copy, but it will need cleaning up a bit to fit in with an "official" setting.  I can be part of that if people like this idea.

**Comment by samccone** [comment]
:+1: :+1: yay

**Comment by benmccormick** [comment]
Also something like this should work in this slide from @jmeas's BackboneConf talk: https://www.youtube.com/watch?v=EvQnntaqVdE&list=PLlgxAbM67lYIGw8DnANC7VgREbzJRQged#t=244  I think it does a good job of motivating why you'd want a "framework on top of a framework", and how Marionette complements Backbone

![james_smith_-_marionette_the_backbone_framework_-_youtube](https://cloud.githubusercontent.com/assets/1899941/6358745/e67469d0-bc3b-11e4-8316-e8e8465bd12a.png)

**Comment by benmccormick** [comment]
Here's a cleaned up version of the post in Markdown form: https://gist.github.com/benmccormick/7fb48e9c411db00c0094

I removed the site specific stuff and the section critiquing the marionette docs from not having this type of information... since clearly that is being resolved.  I did add a quick attribution/linkback, but won't complain if you remove it.

**Comment by jdaudier** [comment]
This is added to the preliminary guides: https://github.com/marionettejs/guides/blob/master/why_marionette.md
