### ISSUE TITLE
Webpage is showing up partially translated to French or Spanish for some users

### ISSUE THREAD

**Issue by sarkasm** [marionettejs/marionettejs.com#383]
Using Chrome, I am currently seeing the http://marionettejs.com/ website partially translated in French, another user around me is seeing it in Spanish.  In other browsers the site appears in English.  The web browsers in question were set to the default English language.

Browser: Chrome Versions 41.0.2272.104 (64-bit) and 42.0.2311.60

French: 
![img](https://s3.amazonaws.com/uploads.hipchat.com/18058/118022/e9FvDFiMMSpXDs6/Marionette_js_%E2%80%93_Le_Framework_Backbone.png)

Spanish:
![img](https://s3.amazonaws.com/uploads.hipchat.com/18058/503462/y0DJnnIq8jkg4Mo/Marionette_js_%E2%80%93_The_Backbone_Framework.png)

**Comment by peterblazejewicz** [comment]
@sarkasm Thanks for the report!
It looks like completely random - I'm getting Japanese (though I'm learning Japanese - coinsidence?)
I think that's the service problem, their web page is also translated:
https://www.transifex.com/
![image](https://cloud.githubusercontent.com/assets/14539/6875580/34b89da4-d4c0-11e4-86ed-712e6b647777.png)
cc @samccone 

Do you observe that problem only in Chrome btw? (I do)

**Comment by peterblazejewicz** [comment]
Their new code works differently under Chrome:
https://twitter.com/blazejewicz/status/581543330611388416

**Comment by nbasili** [comment]
Hi there,

There was an issue with Transifex Live in detecting the source language of the website (English) as a possible language preference in Chrome. This issue should be now fixed. Can you please verify? Note that local storage must be reset for the changes to take effect otherwise that last used language option is selected.

Also there is another issue in the marionette website. Although Transifex Live is enabled, the language selector is intentionally hidden by marionette css. So a user has no option to switch language if for some reason she wishes to.

The only way it can be done the way it is right now, is to use something like 
http://marionettejs.com/?lang=en
that will force Transifex Live in selecting English or any other locale. The language detection pattern is described here: http://docs.transifex.com/developer/live/webmasters#lang-detection-pattern

So I would suggest that you either enable the default language selector of Transifex Live or implement a custom language selector by following the sample here: http://docs.transifex.com/developer/live/webmasters#creating-a-custom-language-selector

**Comment by samccone** [comment]
:+1: I will enable it, I only had it hid because I was trusting the local detecting magic, but it seems clear that people do not like it.

**Comment by samccone** [comment]
thanks for following up @nbasili really awesome of you guys

**Comment by sarkasm** [comment]
I can verify that clearing the language bits in my localstorage cleared this up for me this morning

**Comment by peterblazejewicz** [comment]
@nbasili Nikos, Thanks! Worked!
