### ISSUE TITLE
example apps buttons and links don't work on mobile

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#404]
Except for Streamus 

any idea why @peterblazejewicz ?

**Comment by peterblazejewicz** [comment]
@jdaudier 
This is fixed by #407 
The elements overflow other elements - so no pointer events are passed. 
You can test such problems in Google Chrome Dev Tools - as they emulate mobile device and touch/pointer in emulation mode just like on real device (*nearly*):
![20150413205714](https://cloud.githubusercontent.com/assets/14539/7123063/c86599b4-e21f-11e4-90c1-6eafc03d08c0.jpg)

**Comment by jdaudier** [comment]
Thanks @peterblazejewicz! LGTM
