### ISSUE TITLE
Add offline feature

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#469]
I think it will be cool if site can work offline. 
E.g. reading doc without any connection will be helpful for people. 

I propose to use [sw-precache](https://github.com/GoogleChrome/sw-precache). 
Bu service worker work on with sites which are using HTTPS.
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

> Service workers only run over HTTPS, for security reasons. 

I think we have an issue regarding to this #454 
@samccone can you look at this? Can we make it works for github-pages?

**Comment by denar90** [comment]
Found this [article](https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html). Think it might be useful for migrating on `https`.

**Comment by jdaudier** [comment]
We will lose our custom domain though it seems.

**Comment by denar90** [comment]
Do you think
> On CloudFlare, go to your domain’s ClouldFlare settings and set the SSL setting to Flexible SSL.

can somehow affect on our domain?

Also in comments for article found [how to redirect visitor to https](https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-).

**Comment by scott-w** [comment]
Just happened across this, I've setup SSL before for different sites (mostly with AWS CloudFront).

You can either:

1. Keep the CNAME on Github pages and have your CDN pass the Host header through
2. Remove the CNAME and have the CDN swallow the Host Header (just link to the GH Page directly)

In the second, you can get end-to-end encryption and you just point the DNS at the CDN instead of directly at GitHub.

**Comment by paulfalgout** [comment]
https://marionettejs.com/ appears to be working already

**Comment by scott-w** [comment]
So it is

**Comment by denar90** [comment]
🎉
