### ISSUE TITLE
Sprite twitter svg icon in header

### ISSUE THREAD

**Issue by sethkrasnianski** [marionettejs/marionettejs.com#97]
The current hover state flickers since it's requesting the svg, then works seamlessly thereafter. Spriting it or doubling up will fix this.

**Comment by samccone** [comment]
or base64;ing

**Comment by sethkrasnianski** [comment]
:+1:

**Comment by jdaudier** [comment]
Thanks @paulfalgout!  I'd likr to know about this base64 technique though if anyone cares to share.

**Comment by paulfalgout** [comment]
base64 is encoding a data uri right into the src.. so you can take an image or a font file or something and encode it into a string and use it within a css file.  However as far as svgs it's quite possible since they're just plain text files to just use the data uri without base64 as base64 can add some extra weight. http://css-tricks.com/probably-dont-base64-svg/

I'm looking for an easily maintainable solution that's as flexible as possible.. might not be this direction.. I'll do a PR in a little bit

**Comment by jdaudier** [comment]
i think another way is to use the svg as svg and change the fill

**Comment by sethkrasnianski** [comment]
Either way is great. base 64 is particularly great because it requires no assets.

**Comment by paulfalgout** [comment]
@sethkrasnianski the thing with base64 and svg is that it doesn't necessarily buy you anything. With a font or a jpg or something binary, technically I think you could open the file in a simple text editor and copy the binary gobbledygook directly into css, but you're likely to get a special character that breaks your css file in the browser.  base64 solves this problem.  but since xml is all text, converting to base64 typically adds extra characters where they're not needed.  It's more base64 text to represent the svg text.

So for instance this is the same file:
```
url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path fill="#fff" d="M8 2.8l8 7.9-2.4 2.4-5.5-5.5-5.6 5.6L0 10.7z"/></svg>')
```

vs 
```
url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE2IDE2Ij48cGF0aCBmaWxsPSIjZmZmIiBkPSJNOCAyLjhsOCA3LjktMi40IDIuNC01LjUtNS41LTUuNiA1LjZMMCAxMC43eiIvPjwvc3ZnPg==');
```
